# Generated by Django 4.1.7 on 2023-03-12 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_todolist_date_posted_todolist_post_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='post_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.profile'),
        ),
    ]
