# Generated by Django 4.1.7 on 2023-03-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_todolist_post_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
