# Generated by Django 4.1.7 on 2023-03-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_picture.png', null=True, upload_to=''),
        ),
    ]
